//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugstore_003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conceptoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conceptoes()
        {
            this.DetalleLiquidacions = new HashSet<DetalleLiquidacions>();
        }
    
        public int idConcepto { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> porcentaje { get; set; }
        public Nullable<double> total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleLiquidacions> DetalleLiquidacions { get; set; }
    }
}
