//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugstore_003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleLiquidacions
    {
        public int idDetalle { get; set; }
        public Nullable<int> idLiquidacion { get; set; }
        public Nullable<int> idConcepto { get; set; }
        public Nullable<double> monto { get; set; }
    
        public virtual Conceptoes Conceptoes { get; set; }
        public virtual Liquidacions Liquidacions { get; set; }
    }
}
