//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugstore_003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaCompras
    {
        public int idLineaCompra { get; set; }
        public Nullable<int> idCompra { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> precioCompra { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual Productoes Productoes { get; set; }
    }
}
